# ==== config.yml ====

# === Nonce ===
nonce_length: 16 # Länge des Nonce in Zeichen

# === HMAC ===
hmac_block_size: 8 # HMAC-Authentifizierung alle N Zeichen
hmac_tag_length: 12 # Länge des HMAC-Tags im Alphabet-Zeichen
